### ISSUE TITLE
Step 2 - Temporal extent "Today" calendar feature

### ISSUE THREAD

**Issue by ggalibert** [aodn/aodn-portal#1197]
Barely any data collection provides "Today" data access which result in having the "Today" feature in the Temporal extent calendar of step 2 unavailable/useless.

Instead of "Today", a button "Latest" would be a lot more useful to navigate to the latest date where data is available.

**Comment by pmbohm** [comment]
It seems this issue is fixed for netCDF files. As the pickable dates are now limited to available days and `Today` is never available.
It remains a problem for non gridded data however which is due to the information of date range not being available. 
![screen shot 2016-05-02 at 11 40 36 am](https://cloud.githubusercontent.com/assets/1066981/14945755/e90bb67a-105a-11e6-88c7-fea4fcaa6d9f.png)

The issue described above is not simply fixable as the date picker widget behaviour offering a `today` link is not override-able. The whole date picker code would have to be overridden

**Comment by pblain** [comment]
Covered by #1784
