### ISSUE TITLE
Get feature Images not resized

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1339]
Instance name: IMOS
            Environment: production
            App version: 3.29.1
            Build date: Wed Aug 06 15:48:13 EST 2014
            Build number: 35
            Git ref: 87bbe9a621f835493caff90435ebb4206b1f8637

This is an issue that has been seen in the past #849 but as not seeing on Argo any more, comments in old issue were to open a new issue.

Steps to reproduce

Add SRS Bio-optical database colelction to the map and click any point on the layer to display gfi, scroll down to see graph in GFI 

What should happen

GFI opens and when user scrolls to image the image resizes to fit the constraints

What does happen:

Image remains the same so user must expand GFi to see the whole graph

**Comment by evacougnon** [comment]
Can see this issue again

### Steps to reproduce the issue
1. open IMOS SRS Ocean Colour Bio Optical Database of Australian Waters: https://portal-systest.aodn.org.au/search?uuid=97b9fe73-ee44-437f-b2ae-5b8613f81042
2. Click on a data point on the map
3. Get feature popup appears
4. Click on the pin (top right corner) to resize (wider or smaller)

### Expected behaviour
Graph should resize to always be entirely visible (at least horizontally)

### Actual behaviour
Graphs are not adjusting to the overall size of the get feature window

### Screenshots.
![Screenshot from 2023-01-20 14-11-21](https://user-images.githubusercontent.com/5467402/213610229-104990b4-ba0a-4812-b6e5-43948f2f3c09.png)

![Screenshot from 2023-01-20 14-15-44](https://user-images.githubusercontent.com/5467402/213610291-c7ea4709-e6cd-4fbf-8e9e-971dc87bdda5.png)

### What version of the aodn portal are you using?
v4.42.96

### Which browser are you using?
chrome

### Any extra information that might be useful in the debugging process.

**Comment by craigrose** [comment]
@vfisaac 
Fixing this would require code changes in Portal - are we going to close as "will not fix"?

**Comment by vfisaac** [comment]
Agreed - we wont fix this. Closing the issue and will update the test case.
