### ISSUE TITLE
CSV not working for ANFOG layers

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1553]
Instance name: IMOS
            App version: 3.38.1
            Build date: Tue Jan 06 16:22:45 EST 2015
            Build number: 306
            Git ref: 7c92c8bb3b4dd016b4e65fb0e26d09019939109c

Steps to reproduce:

Add either ANFOG collection in the portal subset down so it is not too big a download

Proceed to step 3 and select csv from the download options

What should happen:

Csv Downloaded

What does happen:

Loading indicator shows as if something is happening but then nothing does happen

Note: The other download formats work and can't find any other layer that this happens on

**Comment by jonescc** [comment]
Problem occurred when applying a spatial constraint to the anfog_dm download.

I tracked this back to postgres taking to long to start delivering data using the requested filter - was taking up to 40 seconds to start depending on whether data had been cached before or not, which is way too long as the apache proxy in between times out after 10? seconds.

Postgres is taking such a long time to deliver data because a) there is no spatial index on the measurements geom column, b) the data is requested to be returned in original file, time order and c)  anfog_dm is a massive dataset (122,298,249 records).

I tested adding a spatial index on geom on a copy of the anfog_dm schema and this by itself did not help as postgres decided to use the same index (file id, time) to access measurements so that it would return the data in the correct order without sorting.

Postgres can be quite quick at doing this type of thing with smaller datasets, but anfog_dm is just too big to to be able filter efficiently and return data ordered differently quickly.  Removing the order by from the view results in records being returned instantly when a spatial index is available.

Some possible options here are to:

a) increase timeouts - not a good idea for a synchronous web request
b) remove the order by
c) add an asynchronous option to retrieve data ordered

Any other ideas here?

I'd suggest in the first instance adding the spatial index is added and the order by clause is removed until a better option is added - at the moment the user can't download the data anyway.

**Comment by jonescc** [comment]
I guess upgrading hardware may also help - running aatams on AWS improved performance of sequential scans by 10x which may make synchronous anfog_dm order filtered downloads possible again.

**Comment by danfruehauf** [comment]
:+1: for removing the order_by, seems like that is the real problem here.

**Comment by jonescc** [comment]
Changes made to anfog_dm harvester to remove order by and add a spatial index on geom.
