### ISSUE TITLE
Empty file for BOADAAC with unknown geoserver layer

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1624]
When downloaded as "List of URLs" for an incorrectly configured collection, an empty file is returned (rather than some form of error).

**Steps to reproduce**
1. Configure a collection to include a layer belonging to an allowed geoserver, but non-existent layer.
2. Add collection in portal, download as "List of URLs".

**What should happen**

An error message (or *some* form of feedback) is displayed to the user.

**What does happen**

1. a 500 error is returned from geoserver to the portal server (but this is not visible to the user).
2. an empty file is downloaded.

**Comment by pblain** [comment]
Such a  misconfiguration shouldn't happen in the first place - because config changes should be tested in content-test.  And if it does happen, our AODN content monitor should detect it and hide the data collection.  But until we get our act together the portal should handle it more gracefully, and an alert should be raised.
