### ISSUE TITLE
MARVL endpoint failing

### ISSUE THREAD

**Issue by dnahodil** [aodn/aodn-portal#1639]
On the Portal we have an service that MARL can use to get URLs from IMOS layers. It is currently returning a Grails error page when you try  to access it.

**Steps to reproduce**
Visit this link: https://123.aodn.org.au/imos123/marvl/urlListForFeatureRequest?url=http%3A%2F%2Fgeoserver-rc.aodn.org.au%2Fgeoserver%2Fwms%3FtypeName%3Dimos%3Aargo_profile_layer_map%26SERVICE%3DWFS%26outputFormat%3Dcsv%26REQUEST%3DGetFeature%26VERSION%3D1.0.0%26CQL_FILTER%3DINTERSECTS%28position%252CPOLYGON%28%28152.6220703125%2520-16.919921875%252C152.6220703125%2520-15.77734375%252C152.1826171875%2520-15.77734375%252C152.1826171875%2520-16.919921875%252C152.6220703125%2520-16.919921875%29%29%29&propertyName=url

**What should happen**
You should get a list of URLs

**What does happen**
You get a Grails error page

**Comment by dnahodil** [comment]
Related to #1618 I think

**Comment by danfruehauf** [comment]
I thought we had a monitor for that, but I think I got confused with some other monitors we have.

Either way, worth adding a monitor for that.

**Comment by dnahodil** [comment]
Yeah, we should add a nagios check as part of this fix.

Should be fixed in Portal 3.42.x

**Comment by dnahodil** [comment]
@danfruehauf Actually, I've changed my mind. I don't think I'll bother with a Nagios check. I say that because this code has unit tests and a manual check in Kate's testing regimen. It was just unlucky that this made it to prod despite these two checks so I don't think we need to add a Nagios alert as well.

The unit test didn't pick it up because of the way a key method was mocked. The change in the method signature didn't cause the mocked method to fail. The test has now been updated such that a similar change to the method would fail the test.
The change that caused the bug was a hotfix for a problem in production. So it didn't go through the usual few days of testing.

**Comment by dnahodil** [comment]
Actually, I've changed my mind again. I'll add a nagios check.

**Comment by danfruehauf** [comment]
It's easy. Have a look at 1-nsp-mel - just add another one long URL there.

**Comment by jkburges** [comment]
I think we can and should learn from what happened here.

This is not the first time that a "hot fix" has resulted in a bug in production that is just a bad, if not worse, than the bug being fixed (and which would've been picked up by system testing).

The problem is that it's not feasible to do a full round of system testing for a hot fix such as this, because those tests are done manually.

I think the options in this case are:

1. **never** release to prod *without* a full round of system testing - if the bug being fixed is so bad that it urgently needs to be fixed, then everyone must stop work to do the testing
2. automate the system tests

Thinking that you *may* be lucky enough to get away without testing is irrational, IMO. :fire_engine: 

I don't need to say which option I think would be the most efficient in the long term (as my preferred option also has a lot of other benefits). :earth_asia:

**Comment by dnahodil** [comment]
Nagios check added. See: https://nagios.aodn.org.au/cgi-bin/nagios3/extinfo.cgi?type=2&host=1-nsp-mel.emii.org.au&service=marvlUrlListForFeatureRequest+apache+imos.aodn.org.au%3A443%2F
