### ISSUE TITLE
Not all links on the Data collections page work

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1679]
From a HELPDesk enquiry:

I'm trying to access the link In the IMOS portal web https://imos.aodn.org.au/data_collections.html
that contains 
Salinity, Nutrient, Alkalinity, Oxygen | IMOS National Reference Station (NRS) - Salinity, Carbon, Alkalinity, Oxygen and Nutrients (Silicate, Ammonium, Nitrite/Nitrate, Phosphate)

but I'm getting this error 

Not Found 
The requested URL /Salinity-Nutrient-Alkalinity-Oxygen-|-IMOS-National-Reference-Station-NRS-Salinity,-Carbon,-Alkalinity,-Oxygen-and-Nutrients-Silicate,-Ammonium,-Nitrite/Nitrate,-Phosphate.html was not found on this server.
________________________________________
Apache Server at imos.aodn.org.au Port 443

Steps to reproduce:

Go to the collections link above,

Find the mentioned link and click

What should happen:

Taken to an information page

What does happen:

Get a 404 error

**Comment by danfruehauf** [comment]
I ran a link checker against all the records (https://github.com/aodn/seo/blob/link_checker/verify-links.sh) - that's the only broken one.

This is due to the record having a `/` somewhere in its name. Doesn't matter, the fix below will get rid of those `/` which can generate broken links. Or in other words, it'll generate a little directory hierarchy on the filesystem because of the `/` instead of a proper filename.

This will fix it: https://github.com/aodn/seo/pull/9

**Comment by danfruehauf** [comment]
Expected generated file is:
```
Salinity-Nutrient-Alkalinity-Oxygen-|-IMOS-National-Reference-Station-NRS-Salinity,-Carbon,-Alkalinity,-Oxygen-and-Nutrients-Silicate,-Ammonium,-NitriteNitrate,-Phosphate.html
```

Actual generated file:
```
Salinity-Nutrient-Alkalinity-Oxygen-|-IMOS-National-Reference-Station-NRS-Salinity,-Carbon,-Alkalinity,-Oxygen-and-Nutrients-Silicate,-Ammonium,-Nitrite   /   Nitrate,-Phosphate.html
```
Spaces added for clarity.
