### ISSUE TITLE
Metatdata information not displayed correctly

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1748]
Steps to reproduce:

Select satellite from platform facet list.
Add any SST L3S collection to the map.
On step 2 click the info tab 

What should happen:

See all text as it should read in particular the degrees symbol for lat/long

What does happen:

Degrees symbol is displaying as diamond with question mark inside
![degrees diamond](https://cloud.githubusercontent.com/assets/2906602/7505721/6435153c-f499-11e4-9c1d-1bf047c3b3c0.jpg)

**Comment by keaves** [comment]
Seems to happen with the apostrophe as well
![image](https://cloud.githubusercontent.com/assets/10750046/7508632/dc9144e2-f4c6-11e4-8268-cb843b7cddee.png)

**Comment by anguss00** [comment]
I'll have a look at this

**Comment by danfruehauf** [comment]
This bug happened in systest and production, but NOT on edge and when running locally. Doesn't happen in vagrant.

After some thorough investigation by @anguss00 and myself, including the following:
 * Compare Jenkins builds
 * Compare OS versions of libraries
 * Compare apache configurations
 * Compare tomcat configurations
 * Compare environment variables tomcat is running with

The conclusion is that the culprit is having `LC_ALL=C` in systest and production in the tomcat environment. Now we need to find where this is coming from...

**Comment by danfruehauf** [comment]
`LC_ALL=C` is being added ONLY when chef is restarting the tomcat container on this node. Restarting the tomcat container via regular SSH login will result in no `LC_ALL=C`.

**Comment by danfruehauf** [comment]
Bug opened in Chef:
https://github.com/chef/chef/issues/3367

**Comment by danfruehauf** [comment]
This is a rather subtle bug I think. I had a lengthy discussion about it in the chef IRC channel. We're setting just `LANG=en_AU.utf8` but not `LC_ALL`. Chef then overrides with `LC_ALL=C`.

In chef 12.x there is a method of probing `LC_ALL` as long as you are running on `LANG=en_*`. Chef 11 does not support it. The reason edge has not suffered from that issue is because it was reinstalled with Chef 12.x.

Given that, I think this is a good reason to bulk upgrade to Chef 12.x.

Funny how this subtle bug just propagated all the way through.

**Comment by anguss00** [comment]
@danfruehauf the only issue I have is that I still can't replicate this issue running on the dev box. I run up the portal, set ``LC_ALL=C`` and check that we're running ``LANG=en_AU.utf8`` for the portal process. The bug isn't replicated... so I'm still a little bit worried about this

**Comment by danfruehauf** [comment]
@anguss00 Wouldn't replicate in your grails environment. Either build a war out of that and deploy in vagrant while making sure you have `LC_ALL=C` on the tomcat process, or... wait for Monday and I can give you a hand.
