### ISSUE TITLE
Select button on Step 1 is under title bar

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1790]
App version: 4.6.0
            Build date: Fri Jun 05 14:52:28 AEST 2015
            Build number: 14
            Git ref: d5cbe6fd598ccfd52fb247bc95eca37ef92908d9
Steps to reproduce:

Refresh  http://portal-systest.aodn.org.au/imos123/home#

Look at position of select button

What should happen:

It is at the end of the title bar on the right

![select correct](https://cloud.githubusercontent.com/assets/2906602/8071036/d713bafc-0f49-11e5-9971-a1f0eb46d251.jpg)

What does happen:

It is on the "next line" down under the title bar

![select button](https://cloud.githubusercontent.com/assets/2906602/8071032/c6550bda-0f49-11e5-80d6-4ab68ee18c7c.jpg)

**Comment by dnahodil** [comment]
I'll just add that this problem was evident on @kereid's machine because the grey title bar had been made a bit longer in a recent change, thereby not leaving quite enough room for the 'select' button. The width was only a problem by a few 10s of pixels on her resolution (1280x1024) so it seemed reasonable to shave those pixels off and get the button to the desired place.
