### ISSUE TITLE
Time filtering for aggregatable collections uses "greater/less or equal"

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#1954]
App version: 4.12.1
            Build date: Tue Sep 01 15:30:10 AEST 2015
            Build number: 14
            Git ref: d6c409ad34d5a579c4508c81a0767f7f285fef3e

Same as https://github.com/aodn/aodn-portal/issues/1350

Steps to reproduce:

Add any ncWMS collection to the map such as an ACORN collection

Set the time filter in the subset tab to be the same date for start and end and then choose the end time to be 2 steps after the start ie if the start is 1200 and then there are 1230, 1300, 1330 select 1300.

Proceed to step 2

Click download and select URL

What should happen:

Get a file with 3 URLS

What does happen:

Get a file with only 1 URL

**Comment by dnahodil** [comment]
I think this problem comes from https://github.com/aodn/aodn-portal/blob/d309fbfec077c46bef5b2f8d6da6e83e7d8e7da5/web-app/js/portal/filter/DateFilter.js#L126
I don't know exactly but I think we were meant to be *correcting* the time by 10 or 11 hours (depending on whether daylight savings was in effect) but we are actually just *setting the time* to 10 or 11 o'clock. (maybe?). Also I wonder if this code (which was moved from BaseFilterPanel) was originally only working on the date portion of a JavaScript Date (or perhaps a Moment Date) but that we're accidentally now using it when dealing with the time portion as well.

**Comment by pmbohm** [comment]
"I don't know exactly but I think we were meant to be correcting the time by 10 or 11 hours (depending on whether daylight savings was in effect" 
All our dates are stored in UTC. As far as I understand we would leave them alone. I removed the code that was doing a 'timezoneCorrection' and now date pickers and Step 3 info and amount of files all seem to correlate
