### ISSUE TITLE
Thesaurus provided by wiki not valid xml 

### ISSUE THREAD

**Issue by stevenvandervalk** [aodn/aodn-portal#1968]
Hi guys - thanks for the great docs and code.  Taking part an RDS project to contribute data to the AODN and IMOS.  

Was following the Getting Started in Wiki and 

    Please download the following SKOS vocabulary files:

    Parameter vocabulary

    Platform vocabulary

Linked to rdf/xml that wasn't valid, contain some content and caused an upload error in GeoNetwork.

```
Exc : org.jdom.input.JDOMParseException: Error on line 1800 of docume
nt file:/usr/share/tomcat/webapps/geonetwork/./data/tmp/AODNParameterVocabulary.rdf: The element type "rdf:RDF" must be ter
minated by the matching end-tag "</rdf:RDF>".
```

The files with adjusted syntax that worked for JCU using your GeoNetwork .war are 
* https://github.com/jcu-eresearch/RDS-Marine-Services/blob/update-vagrant-box-to-bento/centos7.1/aodn-vocabulary/AODNParameterVocabulary.rdf
* https://github.com/jcu-eresearch/RDS-Marine-Services/blob/update-vagrant-box-to-bento/centos7.1/aodn-vocabulary/AODNPlatformVocabulary.rdf

**Comment by kereid** [comment]
Hi Steve, thanks for contacting us.

The contribution documentation is currently a work in progress and so we are still fine tuning this and apologise for any inconvenience this may cause, your feedback will be very valuable.  

You have drawn our attention to the fact that the wiki on here is significantly out of date, the most appropriate place to find the contribution documentation is here http://help.aodn.org.au/help/?q=node/71 

Recent discussion within the AODN Technical Advisory Group lead to the provision of links to the vocabularies for the perusal of that group with the understanding that these are not the final versions to be published. Publication is scheduled to occur in approximately 2 weeks. Which will be communicated to the AODN community, Natalia @atkinsn our metadata expert will contact you shortly afterwards with information on accessing these published vocabularies for your use. 

If you would like to test out the process on your private machine please feel free although we emphasis that the urls are most likely to change you can find the link on the help page and it is http://data.aodn.org.au/IMOS/public/eMII/documents/vocabularies/august_2015/ 

Your enquiry has prompted a meeting between various parties (TPAC, AODN)  to take place in the near future (later this week or earlier next) to discuss the best place for users such as yourself to be directed to, we will advise once this has occurred so that you can bookmark the necessary information.

Please let us know if we can provide any further assistance in the meantime.

Cheers,
Kate

**Comment by kereid** [comment]
FYI @JustBerkhout

**Comment by stevenvandervalk** [comment]
Thanks Kate, will try those vocabs. Looking forward to the collaboration. cc @danielbaird

**Comment by atkinsn** [comment]
Hi Steve,
We have recently published the vocabularies - so you can access the latest versions here: https://vocabs.ands.org.au/#!/?publisher=eMarine%20Information%20Infrastructure%20%28eMII%29&p=1. We are currently working on producing some documentation to guide users in the appropriate use of the vocabularies, how to use them in GeoNetwork, how to deal with new versions (file names incorporate the version number) etc. Unfortunately this hasn't progressed as quickly as I had hoped (some staff on leave) - so we hope to provide something to you in the near future. Just wanted to touch base, to assure you we hadn't forgotten about you.
Cheers Natalia

**Comment by stevenvandervalk** [comment]
Hi Natalia
Thanks for not forgetting about me :)   I notice the published contains 9 distinct vocabs, the previous link 4?  Docs would be great but in the meantime I guess we'll just add them to our geonetwork?
Thanks again. 
cc @danielbaird

**Comment by atkinsn** [comment]
Hi Steve, 
Yes, this will be covered off in the documentation - but will attempt to give you a quick explanation now.

So there are 2 organisation vocabs (one contains categories, the other contains all of the organisational entities) - these aren't currently linked up in GeoNetwork (hopefully in the future). But these vocabs can be used offline to guide users in the marking up metadata records with organisation names (in the contact elements) to ensure a standard system of naming. You can see organisation names already in the Portal in Step 1 but they are not currently nested under their categories.

There are vocabs which are actually categories and have the word "category" in their title - these are what provide the top hierarchy (category) in Step 1 portal navigation. These therefore need to be loaded into GeoNetwork as the actual vocabularies nest beneath these categories.

There are 2 parameter vocabs - discovery and sampling. Only discovery parameters are identified in Step 1 at this stage (so please ignore the sampling vocab for now).

So the following vocabs are accessed through the vocab picker in the data parameter element: 
•      ‘parameterName’ is populated by the ‘AODN Discovery Parameter Vocabulary,
•      ‘parameterUnits’ is populated by the ‘AODN Units of Measure Vocabulary’
•      ‘parameterDeterminationInstrument’ is populated by the ‘AODN Instrument Vocabulary’, and
•      ‘platform’ is populated by the ‘AODN Platform Vocabulary’.

I hope this helps, please contact me if you have any further questions.

Cheers Natalia

**Comment by atkinsn** [comment]
Hi Steve,
Sorry, its taken us a little while, but we now have our documentation up online:
http://help.aodn.org.au/help/?q=node/99
I hope this helps you and any associates with moving forward with the AODN vocabularies, GeoNetwork and the 123 Portal infrastructure.
Please feel free to pass on this link as required, and if you have any questions, contact us on: info@aodn.org.au.
Cheers Natalia

**Comment by stevenvandervalk** [comment]
Thanks Natalia.  We'll take a look and get back to you! 
cc @danielbaird

**Comment by smancini** [comment]
Task performed.
Natalia and I will follow up if necessary
