### ISSUE TITLE
No filter options for a collection

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2080]
App version: 4.18.0
            Build date: Wed Nov 25 09:51:20 AEDT 2015
            Build number: 28
            Git ref: 442355c1318504dba3e272fcdd4c9064e0a6d383
        -->
Steps to reproduce:

Add IMOS - AATAMS Facility - Acoustic Tagging Data Repository to the map on step 2 look at all the filters

What should happen:

They have drop down options.

What does happen:

All say "No options available"

Maybe related to:
https://github.com/aodn/aodn-portal/issues/1849

**Comment by pblain** [comment]
Not fixed.  Why is this occurring in systest?

![image](https://cloud.githubusercontent.com/assets/2802359/11885224/e551eac4-a573-11e5-865e-a51ca99bd77a.png)

**Comment by jonescc** [comment]
Fixed in prod by adding a wfs download for this collection - this is a metadata change which hasn't been copied back to systest yet (copies are done weekly).

**Comment by pblain** [comment]
Thanks @jonescc .  @kereid , could you please confirm this once the metadata has been copied?

**Comment by kereid** [comment]
Sure can! @jonescc is it possible to do a manual copy?

**Comment by jonescc** [comment]
OK.  So that wasn't the problem.   Problem is a change made back on 28 October to geoserver to only allow unique value requests for layers matching a regular expression baked into the war. 

Only layers suffixed with _map will work with these changes and the layer name for this collection doesn't.

Probably should be following this convention - not sure why this aatams layer doesn't.

**Comment by jonescc** [comment]
Current geoserver layers not matching this pattern are:

imos:anmn_acoustics
imos:installation_summary
RLS:SurveyList
RLS:M3_DATA
RLS:M2_INVERT_MAP
RLS:M2_FISH_MAP
RLS:M1_MAP

although the rls geoserver instance doesn't have this change as yet.

So - a content issue for us which will become evident if we promote this change to production - not sure about layers for other contributors - are we going to force this naming convention?

**Comment by jonescc** [comment]
Also refer https://github.com/aodn/geoserver-build/commit/4cf41769a1c82a277a6b4809e20897fef065b940

**Comment by pblain** [comment]
Why was the regex matching added?  I don't recall discussing it.

**Comment by jonescc** [comment]
Me neither.  @danfruehauf ?

**Comment by jonescc** [comment]
aodn/geoserver-build@4cf4176 reverted

**Comment by danfruehauf** [comment]
@pblain The regex matching was added because otherwise it is very simple to bring the database down to its knees using a simple filter query on a `_data` layer - **VERY DANGEROUS**.

This is a severe issue and was discussed time and again. The above layers should be fixed to follow the convention. This "fix" is not a fix, it is bringing things back to their broken state.

**Comment by danfruehauf** [comment]
Closing, because a better fix is in place:
https://github.com/aodn/geoserver-build/pull/102
https://github.com/aodn/geoserver-config/pull/310

Tickets opened for bad layer names:
https://github.com/aodn/content/issues/162
https://github.com/aodn/content/issues/161
