### ISSUE TITLE
When I submit a long WPS subset, other jobs may not execute if the long job exceeds execution time limits

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2089]
# To reproduce 

Submit a long netcdf subset job that will exceed the configured execution time limit with one asynch job at a time configured
Submit other short subsets 

# What happens

The long subset times out and so do the short subset jobs as execution time includes queuing time

# What I expect to happen

The long subset job times out, but then the short subset jobs run up to the configure execution time limit

**Comment by jonescc** [comment]
Need to follow up geoserver pull request https://github.com/geoserver/geoserver/pull/1188

**Comment by julian1** [comment]
Upstream geoserver WPS maintainers (@aaime ) are stupid for not recognizing that killing a WPS job before it even starts due to some preceding job exceeding a time limit is unworkable.

We are even more stupid for having wasted 4 months developing a parallel build-system for Geoserver that cannot build our own code.

It is unreasonable to expect upstream Geoserver to merge our code into core when we won't/don't use it ourselves.

It's also unfortunate that geoserver-build traps our extensions (netcdf, layer filters, gogoduck, etc) in a form that prevents them being pushed upstream under Geoserver's community-contribution process. This forces us to bear the maintenance burden and denies their availability to the larger community.

Emii now additionally bears the maintenance burden for extension code we don't even use, but our partners require - such as the SQLServer extension (consider the SQLServer versioning bug-fix).

That Geoserver improvements/fixes we have made - such as reporting the queue position back to the end user (for Gogoduck) are now lost/abandoned simply because we cannot build them, is even more of a waste.

**Comment by pblain** [comment]
Julian's comments:

> We have a parallel build-system for Geoserver that cannot build our own code.
> 
> It is unreasonable to expect upstream Geoserver to merge our code into core when we won't/don't use it ourselves.
> 
> It is also unfortunate that geoserver-build traps our extensions (netcdf, layer filters, gogoduck, etc) in a form that prevents them being pushed upstream under Geoserver's community-contribution process. This forces us to bear the maintenance burden and denies their availability to the larger community.
> 
> Emii now additionally bears the maintenance burden for extension code we don't even use, but our partners require - such as the SQLServer extension (consider the SQLServer versioning bug-fix).
> 
> That Geoserver improvements/fixes we have made - such as reporting the queue position back to the end user (for Gogoduck) are now lost/abandoned simply because we cannot build them, is even more of a waste.
> 
>

**Comment by aaime** [comment]
Unfortunately Github forwarded Julian's original comment laced with direct insults towards me.

I apologize for not following up on that pull request. Back in January I sent this mail to geoserver-devel:

> I believe I'm the reason you're being stuck there... I'm the current maintainer
of the WPS module, the pull request in question is touching very sensitive
parts of the WPS engine and I need some peace and quiet to review it and
make sure it's not breaking something else... unfortunately I 
haven't had much of that in the past few months, and devoted most of it to 
handle easier to review pull requests, bug fixing, and preparing
the code base for the wicket 7 upgrade that we'll start working on tomorrow.
https://wiki.osgeo.org/wiki/GeoServer_Code_Sprint_2016
> I'll try to find some time once I'm back home, but it may well be sometimes
in February at this point.

The situation went from bad to worse since then, and some weeks ago I decided to stop any support using my spare time. I believe somehow similarly to Julian, I had been feeling powerless and had growing disappointment towards the community, so could not justify using any of my spare time for it anymore. This does not mean I won't contribute to GeoServer anymore, but that I've limited my activity during working hours only. 

This is probably not what you wanted to hear, and honestly, it pains me to write it too as I poured years of personal effort in GeoServer, but I've clearly reached my limits here.

**Comment by julian1** [comment]
@aaime 

It was not my intention to tag you, and I apologize unreservedly for any offense my comment may have caused.

My intention was to highlight and contrast how ridiculous our (emii developer) choices have been and the unreasonable expectations we seem to demand of other organisations - that obviously have their own mission, priorities, and resource constraints. 

Open-source software is not supposed to work like that, and the forking model exists for a reason!

I deeply appreciate your comments and the personal insight they carry. I regret that our actions have probably contributed to your sense of disappointment in the community.

Best regards,
Julian

**Comment by pblain** [comment]
Closing as bug is fixed.  We will release to systest even though it's not in the core release yet.
