### ISSUE TITLE
RLS Collection - small logo error

### ISSUE THREAD

**Issue by jachope** [aodn/aodn-portal#2115]
App Version: 4.21.0
Build Date: Wed Jan 27 15:51:57 AEDT 2016
Build Number:
GitRef:

Steps to reproduce:
Search for RLS collection in Step 1 on Systest

What should happen:
RSL collections should be retrieved - with correct formatting, facet data and a small logo

What does happen:
Mapr displayed, no facet information from metadata and the logo takes over the whole frame

**Comment by kereid** [comment]
Maybe related to #2107 for external logos

**Comment by anguss00** [comment]
I believe this has been fixed by https://github.com/aodn/aodn-portal/commit/9cd4048b79a4b1e4e703ec2459e4e42e7c6ea38a. I verified this when I released to systest. However, since then we have hidden the logos as a VIT in response to https://github.com/aodn/aodn-portal/issues/2119. In this case, are we able to close this issue @jachope @kereid?

**Comment by kereid** [comment]
@anguss00 yes this is ok to close I did see it too so can confirm you fixed it.

**Comment by anguss00** [comment]
Awesome, thanks @kereid
