### ISSUE TITLE
New data dowload popup only pulls content from attibution constraints

### ISSUE THREAD

**Issue by atkinsn** [aodn/aodn-portal#2154]
I select the ARGO layer in Portal-systest. I subset the data, and try to download it in step 3.
I expect to see all text related to Resource constraints in the data download popup.
I only see the text from 'attribution constraints', coming from Resource constraints > Creative Commons. There is also relevant text coming from the next Resource constraints element in the metadata record: Resource constraints > Constraints > Use limitation in this records. In other metadata records there may also be relevant text coming from "security constraints" and "legal constraints" depending on how they have marked up their metadata record.

**Comment by kereid** [comment]
This is also seen for AusCPR #2165

**Comment by anguss00** [comment]
I'll look at this

**Comment by anguss00** [comment]
The current status of this issue is as follows:
1. Geonetwork needs to be reindexed following a config change, vocab change, or schema plugins change.
2. I suggest killing the restore op from catalogue-portal to catalogue-systest and using a replicate of prod harvesters to get the metadata into systest. Allows @atkinsn and @kereid to modify records in systest and have user accounts to do so that are managed. Also, no need for a reindex after the restore op.
3. The geonetwork config manager ruby script has been updated to have a reindex flag passed on the command line. Reindex happens automatically when the vocabs are updated using the script.

So what we need to do from here (as a backlog item potentially) is trigger the reindex automagically when any of the events in point 1 occur.
