### ISSUE TITLE
Spatial subset filter not working for IMAS Nearshore temperature monitoring in Tasmanian coastal waters

### ISSUE THREAD

**Issue by xhoenner** [aodn/aodn-portal#2214]
Seen on portal.aodn and imos.aodn. Probably a content issue as well so worth chasing that up with Emma @kereid.

<h3> Steps to reproduce: <h3>

Select the [IMAS Nearshore temperature monitoring in Tasmanian coastal waters] (https://portal.aodn.org.au/search?uuid=71fd0720-44a6-11dc-8cd0-00188b4c0af8). On step 2: Draw a bounding box around the southernmost point (for instance). Go to Step 3.

<h3> What should happen: <h3>

Bounding box filtered applied, listed in Step 3, and resulting CSV having only records for the selected geographic area.

<h3> What does happen: <h3>

Bounding box not listed in the filters applied to the data collection below the data collection name. No spatial subset filtering applied when downloading as CSV.

**Comment by kereid** [comment]
Reply from Emma:
Hi guys,

I follow the Github threads but don't really know how to use them (sorry), hence my direct email reply to this.

Just checked out this layer and it looks like geometry wasn't enabled as a WMS layer filter. I have corrected this and it should work ok now (I think - I can't validate through the IMAS portal because it seems to cache the layer filters for a few hours before it'll reflect new changes).

Let me know if you spot any other issues, or if this doesn't fix the problem.

Cheers,
Emma
