### ISSUE TITLE
Long lists of organisations throw out formatting

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2223]
## Steps to reproduce
1. Add a data collection with a long list of organisations

## What I expect to happen
Formatting in Step 1 still looks acceptable.

## What happens
Formatting looks bad:

![image](https://cloud.githubusercontent.com/assets/2802359/16327568/ce4689a4-3a13-11e6-84b3-6c77a18e170d.png)

**Comment by atkinsn** [comment]
I am not sure to what you mean to fix by making the formatting look "acceptable". I think its an important feature that the Phytoplankton database record stands out as it has lots of organisation affiliations. If you plan to truncate that, I don't necessarily see that as the right approach, as a lot of information will be lost. If it is an issue, I think its more appropriate to move organisation to last on the list of 4, so that Parameters, Platforms and Dates always appear first, and only take up 3/4 lines at most always, then organisations can take up whatever space they want.

**Comment by jonescc** [comment]
Changed to an expandable description for those that want to see the full list of organisations in https://github.com/aodn/aodn-portal/pull/2227

**Comment by pblain** [comment]
@atkinsn -  I only just saw your comment after @smancini asked me to look at it. BTW if you tag me I'll definitely see your posts. 

Anyway, here's what I mean by "Acceptable" - The search results have always been a fixed size, and for good reason - usability.  The long list makes the search results look very different to how they appeared in the past. The bug fix will restore the consistent size of search results, and will allow users to expand the block if they want to see the full list - but this is a quick fix and is still horrible. Good luck finding anything in a wrap around list like that. The layout will need to be re-thought to cope with so many organisations - and to meet your requirements.
