### ISSUE TITLE
GoGoDuck jobs won't start in Systest

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2243]
Steps to reproduce:

Add any gridded collection and sbset to only one day, proceed to step 3 and select download as netcdf

What should happen:

Job starts and get a link to status page

What does happen:

After a bit of a wait see the following error:
Error! The server response was: 'transaction aborted'
Unable to create subsetting job. Please re-check the parameters you provided and try again.

**Comment by anguss00** [comment]
Geoserver-wps-systest restarted. Jstack attached. 
[gs_wps_stack.txt](https://github.com/aodn/aodn-portal/files/370465/gs_wps_stack.txt)

**Comment by jonescc** [comment]
No clues as to what was going on in the jstack - looks like it was doing absolutely nothing.

Given that the same problem could crop up in prod would probably be good to spend a bit of time in systest where a delay of half an hour or so probably doesn't matter trying to work out what the problem is before restating geoserver,
