### ISSUE TITLE
GoGoDuck and THREDDS/ncWMS (may) generate errors when index out of sync

### ISSUE THREAD

**Issue by pblain** [aodn/aodn-portal#2348]
In the event that the index is out of sync with S3 the user should not be confronted with a system error.  I don't know what happens in this situation currently. 

The GoGoDuck should proceed even if it encounters missing files - ideally with some warning being conveyed to the user. In some cases it may just be a timing issue (due to non-transnational indexing)  - or perhaps it is the index, not S3, that is incorrect. In other cases the resulting aggregation will be incorrect, which is BAD. The GoGoDuck has no way to know if it's safe to proceed or not.  Such errors need to be logged, monitored, and dealt with by us as a matter of priority - and we need to ensure that this situation never occurs in the first place, BUT the user should not see system errors or experience a "crashed" GoGoDuck.  Similarly for ncWMS.

**Comment by bhasin85** [comment]
GoGoDuck download failures are logged (within the code) and monitored (using sumo logic). User is displayed with appropriate error message like "Unable to download 2 files out of 2 files"

**Comment by jonescc** [comment]
@bhasin85  - sounds like the GoGoDuck part of this issue has been fixed by your PR?

Currently if a file for a particular timestamp is indexed but doesn't exist on s3 then the layer will not load in step 2 and an exclamation mark will be displayed next to the collection indicating there was some problem loading the layer.  I think this is the correct behaviour in this situation - you don't want to display some other timestamp instead or a not found image.  

To prevent this occurring due to transient mismatches between the index and s3 during pipeline processing then I think the pipeline processing needs to be revisited e.g. to upload to s3 first and then index or delete from index first and then delete from s3 or somehow perform these operations atomically.   I can't see a sensible alternative.

**Comment by bhasin85** [comment]
@jonescc I agree with your suggestion. The user is displayed with appropriate warning (no system error), which means that the inconsistency between the s3 and index is handled properly by ncWms.  The GoGoDuck part is fixed by my PR above.
