### ISSUE TITLE
Date pop-up not correct

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2397]
App version: 4.27.4
            Build date: Wed Nov 30 16:17:30 AEDT 2016
            Build number: 84
            Git ref: bd186299b0d6ad3bf03da25632bc15067a1b065c
Systest:

Steps to reproduce:

Add any collection type in the from date field 2014-6-8

What should happen:

Box around date is highlighted red and a pop up error opens indicating that the date format is invalid and should be yyyy/mm/dd

What does happen:

Box is red but pop up tells me that format should be y-m-d

NOTE
There is no problem with the format changing to - from being / but I;m not sure why it would have been changed anyway and the error message would have needed changing as I believe that is configured by us? So not sure if it may have affected anything else - hence the logging of this bug.

**Comment by pmbohm** [comment]
@kereid @pblain 
The validation message say the format should be `Y-m-d` which is correct for Extjs3.4 date parsing. 
I had a look at modifying this message without making it a long explanation or hard coding the format or adding to the confusion. This proves difficult due to the different ways we are creating date fields, and what exactly what should the message be that would be clearer. 
I suggest that the current behaviour is correct and its not a bug: Previously it showed the format as `Y/m/d` now its `Y-m-d`
