### ISSUE TITLE
No gridded collections have get feature information

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2461]
On Systest

Steps to reproduce:

Add any gridded collection such as radar or satellite.

On step 2 click the collection on the map

What should happen:

Pop up opens with further information about collection

What does happen:

Get message to say no more informsation found at this point

**Comment by pmbohm** [comment]
@akashisama 
This bug is caused by removing the space in the CRS: 'EPSG: 4326'  
https://github.com/aodn/aodn-portal/pull/2452

We will have to discuss this further, but the problem points to the abomination controller i guess?unless the space is following the standards

[failing GFI with 'CRS=EPSG%3A4326'](http://geoserver-systest.aodn.org.au/geoserver/ncwms?LAYERS=srs_sst_l3s_1d_ngt_gridded_url%2Fsea_surface_temperature&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=ncwms&REQUEST=GetFeatureInfo&STYLES=&QUERYABLE=true&CRS=EPSG%3A4326&TIME=2017-04-10T15%3A20%3A00.000Z&BBOX=61.918945%2C-42.759766%2C208.081055%2C-10.240234&INFO_FORMAT=text%2Fxml&QUERY_LAYERS=srs_sst_l3s_1d_ngt_gridded_url%2Fsea_surface_temperature&FEATURE_COUNT=1&SRS=EPSG%3A4326&WIDTH=1663&HEIGHT=370&X=488&Y=145&I=488&J=145&BUFFER=10)


[working GFI with 'CRS=EPSG%3A%204326'](http://geoserver-systest.aodn.org.au/geoserver/ncwms?LAYERS=srs_sst_l3s_1d_ngt_gridded_url%2Fsea_surface_temperature&TRANSPARENT=TRUE&VERSION=1.3.0&FORMAT=text%2Fxml&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=ncwms&REQUEST=GetFeatureInfo&STYLES=&QUERYABLE=true&CRS=EPSG%3A%204326&TIME=2017-04-10T15%3A20%3A00.000Z&BBOX=61.918945%2C-42.759766%2C208.081055%2C-10.240234&INFO_FORMAT=text%2Fxml&QUERY_LAYERS=srs_sst_l3s_1d_ngt_gridded_url%2Fsea_surface_temperature&FEATURE_COUNT=1&SRS=EPSG%3A4326&WIDTH=1663&HEIGHT=370&X=488&Y=145&I=488&J=145&BUFFER=10)

**Comment by pmbohm** [comment]
https://github.com/aodn/aodn-portal/commit/dec15962f0ec080efe07335d9080283ff204707a created the space by 'formatting'.
