### ISSUE TITLE
AUV layer doesn't show platform in results

### ISSUE THREAD

**Issue by akashisama** [aodn/aodn-portal#2506]
**Steps to reproduce:**
In the platform facet click "AUV"

**What should happen:**
The one lonely result ("IMOS - Autonomous Underwater Vehicle (AUV) Facility") should contain AUV platform

**What does happen:**
No platform section in result

**Comment by atkinsn** [comment]
@pblain I think the issue here is actually that the platform in the vocabulary doesn't match how the metadata is marked up. The term is wrong in the vocabulary but correct in the metadata. So this is why it won't appear in the results section. I will rectify this once I have had a chance to chat to Kim about it upon her return in August.

**Comment by pblain** [comment]
@atkinsn - Thanks for that. Makes me wonder why we see a count of 1 in the platform facet. Anyway, I'll add it to the content repo.

**Comment by jonescc** [comment]
Looks like the 'platform' used in the search result is derived by looking up the platform name from the metadata in the platform category vocabulary.  The platform in the metadata doesn't match whats used in the vocabularies and so it can't be found as per @atkinsn's comments.  Perhaps better to use the uri recorded in the metadata for the lookup (would need to index that instead/as well) but there is still an issue with the metadata being able to be out of synch with the vocabulary.   So a content change will fix this but would also be good to revisit how this is done at some point.

**Comment by jonescc** [comment]
Closing as it will be fixed by a content change
