### ISSUE TITLE
Polygon subset inconsistently displayed on step 3 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2538]
Steps to reproduce:

Add an ncWMS collection such as an ACORN collection, also add an non-ncWMS collection such as Argo.

Draw a polygon on step 2 proceed to step 3

What should happen:

User can see they have applied a polygon to any collection.

What does happen:
non ncWMS collection gives indication that "Spatial subset: polygon with max extent (4 co-ordinates)  

NcWMS collection indicates "Spatial subset: (4 co-ordinates listed)"

**Comment by pmbohm** [comment]
@kereid @pblain 

I think this is a feature not a bug.

In the case of the Gridded collection; The spatial subset is sent as a BBOX because that is all that can be handled for subsetting.
In the case of the Non-gridded collection, the database (behind Geoserver) can handle a polygon query, but for berevity we say `Polygon with max extent of is blagh.....` 

<img width="998" alt="screen shot 2017-08-30 at 3 06 38 pm" src="https://user-images.githubusercontent.com/1066981/29856252-f554dc46-8d94-11e7-8666-2891c26fd847.png">

**Comment by pblain** [comment]
@pmbohm - agreed
