### ISSUE TITLE
Selenium browser update failing FacetPlatformTest

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2541]
Test | OS | Browser | Duration | Finished
-- | -- | -- | -- | --
FacetPlatformTest | Win 10 | Firefox 54.0 | 1m 36s | 3d ago
FacetPlatformTest | Win 10 | Firefox 55.0 | 1m 30s | 3d ago
FacetPlatformTest | Win 10 | Firefox 53.0 | 1m 33s | 3d ago
FacetPlatformTest | El Capitan | Firefox 55.0 | 1m 10s | 3d ago

**Comment by bhasin85** [comment]
Able to reproduce

**Comment by akashisama** [comment]
This FacetPlatform test has started failing consistently on chrome browsers as well due to an unrelated issue. Because we haven't yet implemented https://github.com/aodn/backlog/issues/648 the test is failing when it gets to the "aircraft" platform. Two records are getting into the first page, and this test checks first page records to make sure they match with the platform selected in the platform facet. But these two records have multiple platforms and we currently only support one platform within the results section.

For _this_ selenium issue we'll need to pinpoint the problem which is occurring specifically on the new versions of firefox, _not_ the "aircraft" problem which is occurring on all browsers and has a backlog item.

**Comment by bhasin85** [comment]
I think it will make more sense to look into this after we fix https://github.com/aodn/backlog/issues/648

It will be much easier to pinpoint the issue.

**Comment by akashisama** [comment]
Selenium issue fixed by https://github.com/aodn/aodn-portal/pull/2581, test will continue failing until https://github.com/aodn/backlog/issues/648 is implemented
