### ISSUE TITLE
Selenium browser update failing ImosLinkCheckTest

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2548]
Test | OS | Browser | Duration | Finished
-- | -- | -- | -- | --
ImosLinkCheckTest | Win 10 | Firefox 55.0 | 1m 40s | 3d ago
ImosLinkCheckTest | Win 10 | Firefox 54.0 | 1m 31s | 3d ago
ImosLinkCheckTest | El Capitan | Firefox 53.0 | 3m 5s | 3d ago
ImosLinkCheckTest | El Capitan | Firefox 54.0 | 3m 20s | 3d ago

**Comment by bhasin85** [comment]
Unable to reproduce.

**Comment by akashisama** [comment]
The goal of the test is to run through all the external links in the portal and make sure they're accessible.
 
Problem 1:
The records contain links to points-of-truth, which, for portal-edge, are on catalogue-systest. But catalogue systest is blocked to the world. So these tests should be failing on Firefox _and_ Chrome. The reason they're not failing in chrome is a misplaced "break" statement which should be a "continue" statement, causing chrome to break out of a testing loop too early to get around to testing the points-of-truth.

Problem 2.
Neither Chrome _or_ Firefox is failing when we run the tests on our local machines. This is because the test is using Java HttpClient to test the links: the get request is run from our local machines rather than the browserstack browser. Our local machines have access to catalogue-systest whereas Jenkins doesn't.

I'll put up a PR to fix problem 1 so that Chrome starts failing. 
I think there's two options for solving problem 2:
- Don't transform points-of-truth to point to catalogue-systest
- Make the test skip point-of-truth links
