### ISSUE TITLE
No indication of number of files in step 3

### ISSUE THREAD

**Issue by petejan** [aodn/aodn-portal#2578]
In step 3 of the portal there is no indication of the number of files in the collection to be downloaded.

Some list like,

http://www.petejansen.org/thredds/dataTables.html

would allow the user to see what is about to be downloaded, as some downloads are only a few, but a large collection like argo would be 164000 files.

**Comment by kereid** [comment]
Hi @petejan, thank you for this suggestion, we do have this on our backlog (https://github.com/aodn/backlog/issues/670) it has been on there for some time, however due to some other issues and enhancements that were either more urgent or important, this enhancement is still sitting in the list.  I have re-tagged the item so that it can be re-discussed and prioritised again in the next management team pre-planning meeting, and I will notify you of the outcome. 

Closing as noted in backlog.

**Comment by petejan** [comment]
That's not all that helpful, as the backlog repo seems to be private, so you're link returns page not found. Would you not be better to put the link to this issue in your backlog repo?
