### ISSUE TITLE
VCDEM collection with no time stamp fails

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2594]
I don't know how long this has been broken I had it fail in production once but with a different error message and now can't get it to fail again, but it's definitely in systest. I don't ever test this collection/filter function until today as I had a little bit of spare time.  As it was a new collection/filter function it should have been tested by selenium....

I have checked with Alex and there are no selenium tests.

Steps to reproduce:

Add Victorian Coastal Digital Elevation Model (VCDEM 2017) collection to the map proceed to step 3

Select download as netCDF

What should happen:

NetCDF download begins and succeeds

What does happen:

get error: Error! The server response was: 'Forbidden'
Unable to create subsetting job. Please re-check the parameters you provided and try again.

**Comment by anguss00** [comment]
I know what's caused this issue. The systest transform was changed to convert processing.aodn.org.au/wps into processing-systest.aodn.org.au/wps. However, this record is being harvested from an external catalogue; and until this morning still contained a link to geoserver-wps (which is no longer being transformed into the systest equivalent). As the record has been updated on both catalogue-portal and on deakin's catalogue, this will be fixed by running the systest harvest again (which will update the endpoint as appropriate).

**Comment by kereid** [comment]
Ah ok I should have questioned you further before logging :-)

**Comment by anguss00** [comment]
All good! If systesting is finished we can reharvest the metadata and do a quick smoke test if you like?

**Comment by kereid** [comment]
Yes I am done testing let's do that

**Comment by kereid** [comment]
Closing as this was resolved
