### ISSUE TITLE
Geographical bounding box is incorrect in step 1 micromap

### ISSUE THREAD

**Issue by anguss00** [aodn/aodn-portal#2621]
Steps to reproduce:
Go to step 1, view IMOS - ABOS Southern Ocean Time Series (SOTS) - all delayed-mode data collection. Note the micromap shown on the left hand side of the collection.

Expected behaviour:
Correct default geo extent shown in step 1 on the micromap. The default extent is a little way to the south of tassie.

Observed behaviour:
Random geo extent shown in minimap. Australia is not even visible

**Comment by gsatimos** [comment]
Hi @atkinsn. Just found the solution for this issue I've been looking at. There's a record in catalogue-imos where the extent longitudes for one of the polygons have been encoded incorrectly so that they have negative (-) values instead of positive (+). The result in the portal is that the preview of the extents on step1 of the portal just don't get shown.

**IMOS - ABOS Southern Ocean Time Series (SOTS) - all delayed-mode data
uuid: 723a3e85-04ae-40e6-ac2a-237a93d84abe**

**Comment by atkinsn** [comment]
Hi @gsatimos , unfortunately something I can't fix, this information comes from the database - so something for @mhidas to look into :)

**Comment by mhidas** [comment]
The problem is with the data. There's a file in the collection that has negative longitude values. I'll ask the facility to fix it.

**Comment by pblain** [comment]
@mhidas - can the checker be modified to pick this up?

**Comment by mhidas** [comment]
@atkinsn In the meantime we could actually edit the metadata record directly and simply delete the erroneous spatial extent section. It might be a while before the file is fixed and re-uploaded.

**Comment by mhidas** [comment]
@pblain Yes, it can. It just needs to know what range of lat/lon is expected. That's easy for some collections, less so for others (e.g. Argo).

**Comment by atkinsn** [comment]
@mhidas I have edited it, not sure if it will hold.
