### ISSUE TITLE
Systest has weird URL when click AODN logo

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2662]
Steps to reproduce:

Open systest - proceed to step 1 then click the AODN logo to go back to the landing page

What should happen:

See url portal-systest.aodn.org.au

What does happen:

See https://ci-eb-aodn-portal-systest.aodn.org.au/search

**Comment by lwgordonimos** [comment]
This is a template bug, that has popped up because of the change to using cloudformation for deployments:
We need to fix it here in the template to *not* use the "stack_manifest" endpoint in this scenario where we actually want a fixed URL:

https://github.com/aodn/chef-private/blob/master/aws/ebprep/conf/templates/aodn-portal/Portal.groovy.template#L1

**Comment by lwgordonimos** [comment]
Closing this and created an issue, as it is a configuration problem rather than application problem.
