### ISSUE TITLE
More info on the ready-to-download email

### ISSUE THREAD

**Issue by diodon** [aodn/aodn-portal#2669]
When you request several subsetting tasks you will receive two emails for each, and always the file is named by default output.nc. It would be very useful if the email can contain detailed info on the product and the subsetting boundaries. Something like: 

`Your subsetting task
IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite
Spatial: 150W -25S 170E -10N
Temporal: 2015-Jan-01-09:20-UTC to 2015-Jan-31-09:20-UTC
is ready to download using this link....
`

**Comment by kereid** [comment]
@diodon thank you for your suggestion, this issue is already in our Backlog (https://github.com/aodn/backlog/issues/853) of features to implement, however this is a private repository so I will copy the detail below from the item so you can see it. 

Our process is to close this issue now as it already a feature request elsewhere in Github. The issue will need to be prioritised by management and then if successfully accepted into the next iterative work cycle the earliest it would make it to production would be in 4 weeks (iterative cycle is 2 weeks and then it would need to be tested which would take place in the following 2 week cycle).  I will certainly advise you on when the feature has been implemented into production.

Thanks,
Kate


Backlog item details:

Acceptance Criteria
GoGoDuck aggregations generate a zip file (instead of a netcdf file)
The zip file is named IMOS_aggregation_<timestamp>.zip
The zip includes the aggregated netcdf named IMOS_aggregation_<timestamp>.nc
The zip includes a description of the request in a file named IMOS_aggregation_<timestamp>.txt
The request description file includes the title of the data collection, the subsetting parameters, the job id, etc
The zip file includes the metadata in a file with a name that matches the metadata title
The timestamp referred to above is the local time the job is submitted by the user (not the time it starts running)

**Comment by kereid** [comment]
@diodon my apologies I was notified that the backlog I mentioned didn't actually cover what you were requesting it is just similar.  So I've logged a new backlog item for providing information earlier in the process.

**Comment by kereid** [comment]
HI @diodon I'm pleased to advise that these 2 features have now been implemented! Now in both emails that you get from the system the subset filters applied to the collection are listed.  The download file is now provided in a zip file containing the netCDF file and 2 xml files - one the metadata and the other the subset details.

**Comment by diodon** [comment]
Great!!!
