### ISSUE TITLE
URL list should be sorted before given to the user!?

### ISSUE THREAD

**Issue by ocehugo** [aodn/aodn-portal#2686]
The current behaviour is to provide an unsorted file list when simply selecting a whole dataset.

Reproduce:
```
1. search ```radar velocity delayed capricorn``` in step 1
2. select/next.
3. next.
4. Grab URL list
5. List is unsorted
```

Expected:
A list sorted by filename. This would put the files time-ordered given the current URL naming standards.

**Comment by ggalibert** [comment]
Sorting alphabetically is indeed sorting radar files chronologically (not if you ask for more than one site though!) but this is not necessary true for other collections which have a different file naming convention (see ANMN data for example).

Could you please explain the benefit of having a chronologically sorted list?

**Comment by ocehugo** [comment]
@ggalibert didn't get the "for more than one site". If the user requested more than one site, it has to download the list in different files (it would be better if it was aggregated though, but this is another issue). 

Benefits:
It's neat. Users expect things sorted somehow. You request a dataset with a time interval or with several locations, why the list of files is not in chronological order or in location order alphabetically!?

The list could be naturally sorted for other cases...

**Comment by ggalibert** [comment]
> didn't get the "for more than one site"

Forget it, this is not possible! :-) Ok so fair enough for radar collections, yet I was wondering about other collections in general and what is the neatest option: alphabetical or chronological sort.

Sorting alphabetically is not necessarily sorting chronologically within a collection because there are characters before the start date of the dataset that can change depending on the file (datasets can be spread across different folders and the file naming can include subfacility codes and data codes that might be different too). 

For example if you request a list of URLs from the ANMN temperature and salinity collection for the you could get:
```
http://data.aodn.org.au/IMOS/ANMN/NRS/MAI/Temperature/IMOS_ANMN-NRS_TZ_20180228T130000Z_MAI_FV01_MAI-1802-Aqualogger-520T-24_END-20180610T035000Z_C-20180628T011929Z.nc
http://data.aodn.org.au/IMOS/ANMN/NSW/PH075/Temperature/IMOS_ANMN-NSW_TZ_20180227T130000Z_PH075_FV01_PH075-1802-Aqualogger-520T-24_END-20180610T035000Z_C-20180628T011929Z.nc
http://data.aodn.org.au/IMOS/ANMN/NSW/PH100/CTD_timeseries/IMOS_ANMN-NSW_CDSTZ_20180226T190001Z_PH100_FV01_PH100-1802-SBE37SM-RS232-15_END-20180608T012001Z_C-20180628T011930Z.nc
http://data.aodn.org.au/IMOS/ANMN/NSW/PH100/Temperature/IMOS_ANMN-NSW_TZ_20180224T130000Z_PH100_FV01_PH100-1802-Aqualogger-520T-24_END-20180610T035000Z_C-20180628T011929Z.nc
```
This would be sorted alphabetically yet not chronologically.

**Comment by ggalibert** [comment]
I have a PR for acorn layers: https://github.com/aodn/geoserver-config/pull/567

**Comment by pblain** [comment]
Move here: https://github.com/aodn/content/issues/351
