### ISSUE TITLE
CAPTCHA enabled on seventh try not third

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2736]
CAPTCHA has always been set to activate on the third attempt of quick downloads however this time testing it's now on 7 it's probably still not a high number but wondering why it's changed and will it change again?

Steps to reproduce:

Select any gridded collection to be added to step 2. On step 2 subset to a small bounding box and only a day or two for temporal extent.

Proceed to step 3 and select download when the pop up for registering the download opens close it and click the download button again and repeat until the CAPTCHA is activated.

What should happen:

CAPTCHA is activated on the third download

What does happen:

CAPTCHA is activated on the seventh download

![queue](https://user-images.githubusercontent.com/2906602/46841433-9ee04b00-ce13-11e8-9d63-e1df29a5cde0.png)

**Comment by kereid** [comment]
Might be similar to https://github.com/aodn/aodn-portal/issues/2632

**Comment by pmbohm** [comment]
@lwgordonimos 
https://loomchild.net/2011/07/04/servletrequest-getremoteaddr-can-return-ipv6-address/

**Comment by pmbohm** [comment]
The cause is the method `request.getRemoteAddr()` which can return IPv6 or IPv4 addresses. 

Eg: During testing my localhost (client) was identified first as the IPv6 0:0:0:0:0:0:0:1 and subsequently 127.0.0.1
Theoretically the amount of downloads before being asked to enter CAPTCHA is doubled, at no extra real cost to AODN
