### ISSUE TITLE
Error message good but not useful

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2783]
This was seen in Systest twice in a row then the download worked.
![download error](https://user-images.githubusercontent.com/2906602/52687334-880a5a80-2fa5-11e9-8984-c7479446ae6c.png)

Steps to reproduce (maybe)

Add Marvl3 Aus shelf data to the map draw a bounding box - proceed to step 3 and select Download as Temperature observations csv. 

What does happen:

Download failed to start and got the error: an error occurred while downloading this file

What should happen:

Download fails to start and get an informative error - either with information that helps the user understand why or information the user can send to the AODN helpdesk if they so choose and then we can use the information to determine which happened

Note: this addition of the message is a great addition far better than the download not starting and just timing out!

**Comment by pmbohm** [comment]
@kereid I just tried this and it took a while to decide to provide me with the download. Did this take a while for you? Maybe its just a timeout for the request?
If it's the case that the request timed out then the message would be correct because we will not know the true cause.

**Comment by kereid** [comment]
@pmbohm yes I believe it is a time out and that's why we added the error message so it just didn't do nothing, usually try it but it's not just this collection I'm pretty sure the timeout was first seen by @xhoenner on an Animal tracking collection but I can't find the github entry. Perhaps we just need to add a little more to the error message.. 

@ccmoloney would you be happy with adding in to the message to say "please try again"

**Comment by ccmoloney** [comment]
If we think that trying again is likely to work  :)

**Comment by pmbohm** [comment]
This related to a 'contentious' fix by the @gsatimos approved by Don @ccmoloney. Way to go me :)
https://github.com/aodn/aodn-portal/commit/0c687d13c13f6fbf36e2f2d460830eb6f2fd6025
It was to fix  aodn/issues#355

Was there alternative solutions to this problem at the time? Previously the user got nothing at all and now they get a message. This is a better situation.
We most likely expect this message because it has timed out, should we simply assume the user should make a smaller request and change the text to inform the user? (using Openlayer.i18 of course)

BTW: My request was for about 5% of the geographical extent and it nearly timed out.

**Comment by ccmoloney** [comment]
The way it was solved was contentious - not the message  :)  It seems to be providing the expected functionality (a message displayed when a timeout happens) - just need to tweak the message appropriately.
