### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2819]
Console error x4 not sure if we need to action anything as we do support Chrome. I also don't know what doubleclick.net is. Guessing the Wordpress.com would be our userguide.

Steps to reproduce - not sure can get it to come up sometimes but not other times.

A cookie associated with a cross-site resource at http://wordpress.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
search:1 A cookie associated with a cross-site resource at https://wordpress.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
search:1 A cookie associated with a cross-site resource at http://doubleclick.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
search:1 A cookie associated with a resource at http://doubleclick.net/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

**Comment by sachitrajbhandari** [comment]
## New feature in Chrome : [SameSite cookies](https://web.dev/samesite-cookies-explained)

- The new feature comes in Chrome where SameSite=None cookies must also be marked as Secure or they will be rejected. This feature is available as of Chrome 76 by enabling the cookies-without-same-site-must-be-secure flag (https://www.chromestatus.com/feature/5633521622188032).

- Treats cookies as SameSite=Lax by default if no SameSite attribute is specified. This feature is available as of Chrome 76 by enabling the same-site-by-default-cookies flag (https://www.chromestatus.com/feature/5088147346030592).

- In Chrome 80 Stable to be released on  February 4, 2020, SameSite-by-default and SameSite=None-requires-Secure become default behaviour. (https://www.chromium.org/updates/same-site). 

`Note: As these warnings are coming from cross-sites (wordpress.com, doubleclick.net) and not from our website (portal.aodn.org.au), we don’t need to make any changes and the issues need to be fixed by cross-sites. `(https://stackoverflow.com/questions/58191969/how-to-fix-set-samesite-cookie-to-none-warning-chrome-extension)
