### ISSUE TITLE
VIT Download completed 4 days ago cannot be accessed 

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2867]
Seeing in systest:

Set off a download once get the email back saying succeeded wait 4 days (could be less not sure this one was successful Friday 5 June and clicked Tuesday 09 June) click the link to go to the job status page. (or use this one for now https://processes-systest.aodn.org.au/wps/jobStatus?jobId=5e856217-738c-49ea-8c04-913fcfbace85&format=HTML)

Once on the download page click the link to download data.

What should happen:

Data downloads as it should be kept for 7 days as indicated in the email

What does happen:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>689FA932CD759C5F</RequestId>
<HostId>8RH0gp+fjmSTkfSi4OJqM4l2nY7+buqndl/IbqSoCsSXEEfVYKmQ6zhvgSm3ZRM+QfyzhnT4qpU=</HostId>
</Error>

**Comment by lwgordonimos** [comment]
This is now resolved. Note there was no change to the backend operation, it was purely the public read access to the `jobs` prefix.

 The solution was to add the appropriate public read policy back to the bucket:

```json
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::aws-wps-systest/jobs/*"
        }
    ]
}
```

The reason it changed is that the WPS template no longer manages the bucket policy on the bucket (since it doesn't belong to the stack, as we don't want it deleted if the stack is deleted). This was changed because of issues with mixing stack resources and manually created resources in this way.

https://github.com/aodn/aws-wps/pull/301

What this means is that the policy must be added to the bucket manually, which I've done for systest and will make a note in the prod release to update when prod is released.

**Comment by kereid** [comment]
Excellent thank you
