### ISSUE TITLE
temporal filter - using a 'from date' in the future doesn't necessarily give an error

### ISSUE THREAD

**Issue by evacougnon** [aodn/aodn-portal#2931]
### Steps to reproduce the issue
1. Open ANMN temperature and salinity dataset collection: https://portal-systest.aodn.org.au/search?uuid=7e13b5f3-4a70-4e31-9e95-335efa491c5c
2. In the filters, select a timestamp FROM 2023-01-30 (in the future)
3.

### Expected behaviour
A warning should say "No data is available using your chosen subset."

### Actual behaviour
No error is shown, clicking on the mooring site `NWSROW` , the Get Feature Info modal shows available data until 9 Sep 2024

### Screenshots.
![Screenshot from 2023-01-20 13-44-14](https://user-images.githubusercontent.com/5467402/213606940-7f25cff3-ef37-45dc-aa76-674eb0c2eeb9.png)

### What version of the aodn portal are you using?
v4.42.96

### Which browser are you using?
chrome

### Any extra information that might be useful in the debugging process.
This might be a data issue rather than a Portal issue, raising it here as seen during Portal testing, might be moved to the content repo.
FYI @mhidas moorings are recording in the future

**Comment by mhidas** [comment]
> FYI @mhidas moorings are recording in the future

Thanks @evacougnon - yeah, it's the first data from the "Observing the Future" New Tech Proving sub-facility -- they're sending the data back to us through a time machine :yum:

Good pick-up! I can confirm the issue is with the data. There's one file that contains future timestamps. The db/geoserver/Portal are just faithfully passing on that metadata to the user...

I will ask the facility to investigate.

**Comment by mhidas** [comment]
Ok, so the file in question does have erroneous timestamps in it (due to instrument malfunction). Our usual approach in these cases has been to keep all the original data in the file, appropriately flagged and with comments to explain what happened. This has been done in that file. An unfortunate side-effect in this case is that the collection looks like it contains future data (but only for another year or so...).

I would suggest for Portal testing this should just be ignored. If you need a test case that creates a "No data is available using your chosen subset." warning, pick a From date further in the future, or combine the From date with a Site Code filter? Or use a different collection?

**Comment by evacougnon** [comment]
Thanks @mhidas 

@vfisaac do you think we need to disable future dates in the portal? For instance, in the temporal filters, disable dates in the future, so a user cannot pick futuristic dates? Or do we leave it as it is now, knowing future dates can exists in some files for this collection and it's okay as it is well described in the file?

**Comment by craigrose** [comment]
My 2 cents: Leave it as it is. The Portal should be an accurate reflection of the actual data it links to. If there is data recorded with future dates and dates are limited in portal then users will find it harder to filter for it.

**Comment by craigrose** [comment]
Related test cases:
https://aodn.testrail.com/index.php?/cases/view/250  - OK, no changes needed
https://aodn.testrail.com/index.php?/cases/view/34832
