### ISSUE TITLE
Date facet filter not working 

### ISSUE THREAD

**Issue by Chetnamann** [aodn/aodn-portal#2959]
### Steps to reproduce the issue
03/04/2023 pending issue from iteration 251 testing: https://github.com/aodn/aodn-portal/issues/2955

Open Date facet "Date (UTC)"

The "Go" button should be disabled, try clicking on it

Enter valid start and end dates

Click "go" button

first click of "go" should do nothing as it remains inactive

Second click of go button after dates set should return results applicable to only those dates

GH #819

### Expected behaviour
Second click of go button after dates set should return results applicable to only those dates

### Actual behaviour
doesn't return results filtered to dates

### What version of the aodn portal are you using?
4.42.104

### Which browser are you using?
Chrome

**Comment by craigrose** [comment]
This is only an issue in systest. Looks like a content issue. I suspect that GN harvester has not harvested all the required records or there is a problem with the transform used by the harvester.

**Comment by craigrose** [comment]
@sqbaillie @digorgonzola @Chetnamann @evacougnon 
I checked into this and found that https://catalogue-systest.aodn.org.au has been harvesting from catalogue-portal daily since it was last deployed. This results in metadata that is not static and hence returns unexpected results in the searches used in tests. For tests to be valid the metadata needs to be cleared from the systest-catalogue and re-harvested at the beginning of each test cycle then not harvested again during the cycle.  This is why we have [this instruction](https://www.notion.so/imos-world/SysTest-Release-479f07d8030b426b9a4ba8649b4ba9fa?pvs=4#cdf259f5b66a4479b42488008ad4450a) in the systest deployment. I can see how that would have been missed if a decision at some point was made to not destroy/re-deploy catalogue-systest.

**Comment by craigrose** [comment]
I think this is working now since we destroyed, deployed and harvested only once.
